from enum import Enum


class DecisionType(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ClaimStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    DECIDED = "DECIDED"


class RejectionCode(str, Enum):
    POLICY_INACTIVE = "POLICY_INACTIVE"
    WAITING_PERIOD = "WAITING_PERIOD"
    MEMBER_NOT_COVERED = "MEMBER_NOT_COVERED"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    ILLEGIBLE_DOCUMENTS = "ILLEGIBLE_DOCUMENTS"
    DOCTOR_REG_INVALID = "DOCTOR_REG_INVALID"
    DATE_MISMATCH = "DATE_MISMATCH"
    PATIENT_MISMATCH = "PATIENT_MISMATCH"
    SERVICE_NOT_COVERED = "SERVICE_NOT_COVERED"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    ANNUAL_LIMIT_EXCEEDED = "ANNUAL_LIMIT_EXCEEDED"
    SUB_LIMIT_EXCEEDED = "SUB_LIMIT_EXCEEDED"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    NOT_MEDICALLY_NECESSARY = "NOT_MEDICALLY_NECESSARY"
    EXPERIMENTAL_TREATMENT = "EXPERIMENTAL_TREATMENT"
    COSMETIC_PROCEDURE = "COSMETIC_PROCEDURE"
    LATE_SUBMISSION = "LATE_SUBMISSION"
    DUPLICATE_CLAIM = "DUPLICATE_CLAIM"
    BELOW_MIN_AMOUNT = "BELOW_MIN_AMOUNT"
